---
name: Spear PHPUnit Runner
description: A GitHub action to run PHPUnit and record test coverage
branding:
  icon: check-circle
  color: green
runs:
  using: composite
  steps:
    - run: |
        pwd
        
        [[ -f entrypoint.sh ]] && echo "Found entrypoint" || echo "Entrypoint script not found"
        docker run --rm \
          -v $(pwd):/src \
          -w /src \
          -e INPUT_TARGETDIR=${{ inputs.targetDir }} \
          -e SKIP_SECRETS=1 \
          -e SKIP_SERVICES=1 \
          --entrypoint=/src/entrypoint.sh ${{ inputs.dockerImage }}
      shell: bash
inputs:
  dockerImage:
    description: Name of docker image to use to run tests
    required: false
  targetDir:
    description: Target Directory
    required: true
  options:
    description: Options to append to phpunit command
    required: false
outputs:
  success:
    description: "'true' or 'false'"
    value: ""
  summary:
    description: A short description of the results, including the number of assertions, failures, errors, etc.
    value: ""
  result-text:
    description: "'PASS' or 'FAIL'"
    value: ""
  result-emoji:
    description: A different emoji depending on whether the tests passed or failed.
    value: ""
