name: Spear PHPUnit Runner
description: A GitHub action to run PHPUnit and record test coverage
branding:
  icon: check-circle
  color: green
runs:
  using: composite
  steps:
    - run: |
        docker run --rm -it \
          -v $(pwd):/src \
          -w /src \
          -e INPUT_TARGETDIR=${{ inputs.targetDir }}
          --entrypoint=./entrypoint.sh ${{ inputs.dockerImage }}
      shell: bash
inputs:
  dockerImage:
    description: Name of docker image to use to run tests
  targetDir:
    description: Target Directory
    required: true
  options:
    description: Options to append to phpunit command
    required: false
outputs:
  success:
    description: "'true' or 'false'"
  summary:
    description: A short description of the results, including the number of assertions, failures, errors, etc.
  result-text:
    description: "'PASS' or 'FAIL'"
  result-emoji:
    description: A different emoji depending on whether the tests passed or failed.