name: Spear PHPUnit Runner
description: A GitHub action to run PHPUnit and record test coverage
branding:
  icon: check-circle
  color: green
runs:
  using: docker
  image: Dockerfile
inputs:
  targetDir:
    description: Target Directory
    required: true
  options:
    description: Options to append to phpunit command
    required: false
